import os
import yaml
from google import genai


class AIService:
    """
    A service to interact with a Large Language Model (LLM) using the new Google GenAI SDK.
    """
    def __init__(self, config_path='config.yaml'):
        """
        Initializes the AIService.

        Args:
            config_path (str): The path to the configuration file.
        """
        with open(config_path, 'r') as f:
            self.config = yaml.safe_load(f)['ai_service']
        
        self.api_key = os.environ.get("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError("Gemini API key not found. Set the GEMINI_API_KEY environment variable.")
        
        # using the new centralized Client object from google-genai SDK
        self.client = genai.Client(api_key=self.api_key)
        self.model_name = self.config['model']

    def generate_review(self, analyzed_diff):
        """
        Generates a review for the given analyzed diff.

        Args:
            analyzed_diff (dict): The analyzed diff information.

        Returns:
            str: The generated review.
        """
        print("Generating AI review...")

        file_reviews = []
        for file in analyzed_diff["files"]:
            for chunk in file["chunks"]:
                prompt = self._build_file_prompt(analyzed_diff, file['file_name'], chunk)
                # using the new client.models.generate_content() API
                response = self.client.models.generate_content(
                    model=self.model_name,
                    contents=prompt
                )
                file_reviews.append(response.text)
        
        # generating the final formatted review with header and footer
        return self._format_final_review(analyzed_diff, file_reviews)

    def _format_final_review(self, analyzed_diff, file_reviews):
        """
        Formats the final review with a nice header, file reviews, and footer.

        Args:
            analyzed_diff (dict): The analyzed diff information.
            file_reviews (list): List of individual file reviews.

        Returns:
            str: The formatted final review.
        """
        num_files = len(analyzed_diff["files"])
        
        # building the header with summary stats
        header = f"""## 🤖 AI Code Review

> **PR:** {analyzed_diff['pr_title']}
> **Files Reviewed:** {num_files}

---

"""
        
        # joining all file reviews
        body = "\n\n---\n\n".join(file_reviews)
        
        # building the footer
        footer = """

---

<details>
<summary>📚 <b>Review Legend</b></summary>

| Severity | Meaning |
|----------|---------|
| 🔴 **Critical** | Must fix before merging - bugs, security issues |
| 🟠 **Warning** | Should fix - potential problems |
| 🟡 **Suggestion** | Nice to have - improvements |
| 🟢 **Praise** | Good practices worth noting |

</details>

---

*This review was generated by an AI assistant. Please verify suggestions before applying.*
"""
        
        return header + body + footer

    def _build_file_prompt(self, analyzed_diff, file_name, chunk):
        """
        Builds the prompt for reviewing a specific file chunk.

        Args:
            analyzed_diff (dict): The analyzed diff information.
            file_name (str): The name of the file being reviewed.
            chunk (str): The diff chunk to review.

        Returns:
            str: The prompt for the LLM.
        """
        prompt = f"""You are an expert code reviewer. Review this code change with a focus on quality, security, and best practices.

## Context
- **PR Title:** {analyzed_diff['pr_title']}
- **PR Description:** {analyzed_diff['pr_body'] or 'No description provided'}

## File: `{file_name}`

```diff
{chunk}
```

## Your Review Format

Please structure your review EXACTLY as follows:

### 📄 `{file_name}`

**Summary:** [One sentence describing what this change does]

**Findings:**

[For each issue found, use this format:]

- 🔴 **Critical:** [Issue description]
  - **Line:** [approximate line number or range]
  - **Problem:** [What's wrong]
  - **Suggestion:** [How to fix it]
  ```suggestion
  [Code suggestion if applicable]
  ```

- 🟠 **Warning:** [Issue description]
  - **Line:** [approximate line number or range]  
  - **Suggestion:** [How to improve]

- 🟡 **Suggestion:** [Improvement idea]
  - **Why:** [Brief explanation]

- 🟢 **Praise:** [What was done well]

**Checklist:**
- [ ] [Actionable item 1]
- [ ] [Actionable item 2]

---

**Rules:**
1. Be concise but specific
2. Always explain WHY something is an issue
3. Provide code suggestions when possible
4. If the code looks good, say so briefly with a 🟢 Praise
5. Focus on: bugs, security, performance, readability, best practices
6. Don't nitpick formatting if it's acceptable
7. Skip sections that don't apply (e.g., no Praise if nothing noteworthy)
"""
        return prompt